### ISSUE TITLE
geographic_area_name missing in three schema

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/rdl-data#18] opened 2020-12-01 15:00 UTC
Hazard.event_set.geographic_area_name exists; not in GED4ALL, Loss, MOVER.
Include

**Comment by stufraser1** [comment] 2020-12-18 09:45
see also https://github.com/GFDRR/rdl-data/issues/4

**Comment by matamadio** [comment] 2021-01-19 14:37
Close as duplicate of #4 and #27

**Closed as completed by matamadio** 2021-01-19 14:37 UTC
Labels: Q1-2021 schema updates
